### ISSUE TITLE
坑爹公司目录更新

### ISSUE THREAD

**Issue by xiaoxiao29** [iamzko/TaiYuanRubbishCompaniesList#15]
公司名称：山西森甲能源科技有限公司
原因：不发工资

**Comment by edgexie** [comment]
> 公司名称：山西森甲能源科技有限公司
> 
> 原因：不发工资

那两天还在boss上看到这家公司，为什么不发工资？

**Comment by xiaoxiao29** [comment]
常年在招人，3个月了陆续走了10多个，公司业务不行。

**Comment by edgexie** [comment]
> 常年在招人，3个月了陆续走了10多个，公司业务不行。

现在这公司还在boss上活跃呢。没给你发工资，你没去维权？或者躺他们办公室门口。还有这无赖公司呢？

**Comment by xiaoxiao29** [comment]
之前拖了好几个月，现在是离职了的发了，在职的还没

**Comment by iamzko** [comment]
已添加。
