### ISSUE TITLE
我再提供几个公司

### ISSUE THREAD

**Issue by AndroidNullPointException** [iamzko/TaiYuanRubbishCompaniesList#2]
山西映派科技有限公司--法人 王飞  拖欠工资 一到发工资的时候就请大家吃饭并且让管理人员各种理由说服大家 关键老板是个被执行人 一定注意他开的其他公司也不要去 拖工资没商量
山西翌日普兰科技有限公司--法人 赵培焱 拖欠工资 没投资就画饼 有投资就霍霍 一晚上四万的会所玩
山西机契之星科贸有限公司--老板不是法人 所以请注意 拖工资 没商量 办公地点是那种公共的 大家一起用 开发电脑租的人家的 配置特低 画饼特大 超越微信 主要老板是中专 无素质 吃完蒜不停的在你跟前打嗝

**Comment by iamzko** [comment]
老哥你这是经历了什么 :joy:

**Comment by AndroidNullPointException** [comment]
> 老哥你这是经历了什么 😂

五万的工资就是这几家欠的

**Comment by iamzko** [comment]
好吧，已更新。
