### ISSUE TITLE
可以新增几个公司吗

### ISSUE THREAD

**Issue by somethingsky** [iamzko/TaiYuanRubbishCompaniesList#3]
遇到了几个垃圾公司，能帮忙添加到列表里吗

**Comment by iamzko** [comment]
您说

**Comment by somethingsky** [comment]
公司名称：山西捷冠科技有限公司


情报：做c++开发的要被安排去天津，因为母公司在天津，美其名曰培训一个月，实际上去了不让走，太原工资天津干活，没有出差补贴！（而且天津公司地处天津偏远郊区，距离天津市区很远）；因为山西公司在忻州成立，太原分部交的也是忻州的社保，工资要压一个月，第二个月月底才能给发！
------------------ 原始邮件 ------------------
发件人:                                                                                                                        "iamzko/TaiYuanRubbishCompaniesList"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月19日(星期四) 中午1:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [iamzko/TaiYuanRubbishCompaniesList] 可以新增几个公司吗 (Issue #3)





 
您说

**Comment by iamzko** [comment]
已添加
